### ISSUE TITLE
New version of Love! 11.0

### ISSUE THREAD

**Issue by drhayes** [Cronos87/love2d-docset-generator#1]
It's time to re-generate the docset and make a PR to https://github.com/Kapeli/Dash-User-Contributions.

If I can get my Python env straight soon I'll do it. 👍

**Comment by Cronos87** [comment]
Indeed! I checked not long ago but I was still on 0.10.2.

Thank you! I'll do it today, don't worry 😉

**Comment by Cronos87** [comment]
https://github.com/Kapeli/Dash-User-Contributions/pull/1836

Voilà!

**Comment by drhayes** [comment]
Sweet! Thank you very much.

**Comment by Cronos87** [comment]
You're very welcome.

**Comment by Cronos87** [comment]
Docset are now available.
