### ISSUE TITLE
Build the version 11.3

### ISSUE THREAD

**Issue by Cronos87** [Cronos87/love2d-docset-generator#2]
Buid done. Need to publish it this week.

**Comment by Cronos87** [comment]
Incoming https://github.com/Kapeli/Dash-User-Contributions/pull/2594

**Comment by Cronos87** [comment]
OK! 11.3 released!

**Comment by flamendless** [comment]
Hi, but where is 11.3?

**Comment by Cronos87** [comment]
It is available to download on Dash. But If you don't use Dash, I can add the docset on the repo.

![image](https://user-images.githubusercontent.com/1923206/89295249-fe4ec100-d660-11ea-9300-745d91259472.png)

**Comment by flamendless** [comment]
Please do. I use Zeal

**Comment by Cronos87** [comment]
Sure, let me do it in my free time. I will do it as soon as possible.

**Comment by scillidan** [comment]
@flamendless feed it use `https%3A%2F%2Fraw.githubusercontent.com%2Fhashhar%2Fdash-contrib-docset-feeds%2Fmaster%2FLove2d.xml`
See https://github.com/hashhar/dash-contrib-docset-feeds/blob/master/Love2d.xml
